### ISSUE TITLE
Fails to build without libvncclient

### ISSUE THREAD

**Issue by jbeich** [any1/wlvncc#10]
After 23d1c8294367 system libvncclient is no longer required by meson.build. However, some libvncclient headers are missing in the tree.

```c
$ meson setup /tmp/wlvncc_build
$ meson compile -C /tmp/wlvncc_build
[...]
In file included from src/vnc.c:27:
include/rfb/rfbclient.h:41:10: fatal error: 'rfb/keysym.h' file not found
#include <rfb/keysym.h>
         ^~~~~~~~~~~~~~
1 error generated.
```

**Comment by any1** [comment]
This should be fixed now. I added the missing headers and took some steps to keep from accidentally including libvncclient's puplic API.

**Comment by jbeich** [comment]
Builds fine now without libvncclient.
