### ISSUE TITLE
Which gbm package is used?

### ISSUE THREAD

**Issue by mkg20001** [any1/wlvncc#30]
Currently trying to package this for nixpkgs

We have rPackages.gbm which is gbm (the old version) on cran
https://cran.r-project.org/web/packages/gbm/

I'm not sure whether this is the right package

While compling I'm getting this error

```
/nix/store/0zcfsz4iy2p9ibm7i55xx550zkclf1f5-r-gbm-2.1.8.1/include/gbm.h:18:9: fatal error: vector: No such file or directory
```
which stems from the gbm.h file using c++ things when included from c.

I'm also not sure if I'm doing something wrong here

**Comment by any1** [comment]
That's definitely the wrong gbm. The right one is provided by mesa.
