### ISSUE TITLE
input inhibitor

### ISSUE THREAD

**Issue by NDagestad** [any1/wlvncc#4]
Hi, I have a working first draft for capturing inputs with the wlr input inhibitor protocol, would you be interested in that ?
For now it captures all inputs while the window has focus, and no input when the focus is lost or when a special key is pressed (hard-coded to F12 for now but It'd be nice to have it configurable)

**Comment by any1** [comment]
Yeah, sure. It's a useful feature.

**Comment by littlestaryyf** [comment]
Hello NDagestad ,my lvncc viewer can not  use touch screen,the issues is similarity to your's?

**Comment by littlestaryyf** [comment]
Hello NDagestad ,my lvncc viewer can not  use touch screen,the issues is similarity to your's?

**Comment by NDagestad** [comment]
No, my post had nothing to do with handling touch inputs, the WIP PR is #5 but I havent looked at it in a while and don't use wayvnc in my day to day life anymore. If somebody wants the feature they can feel free to continue form where I left off.
I'll close this issue since it doesn't really has any use here.
