### ISSUE TITLE
graphical prompt for password

### ISSUE THREAD

**Issue by quite** [any1/wlvncc#8]
This would be very useful. Alternative, reading password from stdin could be used, and scripted around.

**Comment by cwegener** [comment]
I wonder if it would be best to use an external tool for that. e.g. `bemenu`

**Comment by je-vv** [comment]
Also, using -passwd ~/.vnc/passwd`, which keeps the password encrypted and created by the VNC server if called by non root, then one copies it over to the client.  That client option is available on tigervnc for example.

**Comment by je-vv** [comment]
For me the gui password prompt is the best, particularly if wlvncc is not called through CLI on a terminal, but rather from a *.desktop and wofi for example.  Alternatively providing a vncpasswd utility/script to create the `~/.vnc/passwd` file with the password somehow obfuscated, and supporting something like `-passwd` to allow using the created `~/.vnc/passd` file, can be an option .  But for security it's way better a GUI prompt for the password.

**Comment by rpodgorny** [comment]
this is what i currently use:
```
  expect -c "
spawn wlvncc ${HOST}
expect Password:
send ${PASSWD}\r
interact
"
```
...still, i would prefer if there was a way without the "except" trickery.

**Comment by aidanharris** [comment]
I don't even get a prompt, just the "Unknown Authentication" error. I guess this is a different issue.

**Comment by any1** [comment]
Well, I'm calling it done.
